name: Run tests

on:
  push:
    branches: [main]
    paths:
      - "dist/**"
      - "src/**"
      - "tests/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "dist/**"
      - "src/**"
      - "tests/**"
      - ".github/workflows/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node (${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build files
        run: npm run build

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
